class CreateProducts < ActiveRecord::Migration[5.2]
  def change
    # This file was generated by running following command in the command-line:
    # > rails g model product title:string description:text price:integer
    # Always check your migration file before running rails db:migrate!
    create_table :products do |t|
      t.string :title
      t.text :description
      t.integer :price

      t.timestamps
    end
  end
end
# Make sure you have run:
# > rails db:create
# to initialize your database. This only needs to be run once. Once your
# database is created, then you can run your migrations

# After you create the migration file, and your migration is correct and ready
# to be migrated:
# > rails db:migrate

# NOTE:
# If, after you ran the migration, you realized you had an error in your
# migration file, then you need to either:
# 1. rollback the migration (undoes the most recent update to the db schema):
# > rails db:rollback
# After this successfully run (you will see output in the terminal that shows
# the table was dropped), you are able to modify your previous migration file
# (fix typos, etc) and can, now, rerun the migration command:
# > rails db:migrate
# 2. Create a new migration that updates the products table:
# > rails g migration helpful_title_of_file_the_describes_what_is_being_updated
# After this, a file will be generated for you. You can then modify the product
# table. Rerun the migration command:
# > rails db:migrate
